### ISSUE TITLE
Why does the connect to localhost:1883 not work?

### ISSUE THREAD

**Issue by dongkaipo** [oliverlorenz/phpMqttClient#12]
And how can i do it ? Is there some examples ? Thank you very much!

**Comment by dongkaipo** [comment]
```
$connector->onConnected(function() use ($connector) {
            $connector->publish('test', 'example message',1);
            $this->info('Connected');
});
$loop->run();
```

`onConnected` method not work, and i can find the client info from websocket, but cannot receive anything from reactphpmqtt.

![-1](https://cloud.githubusercontent.com/assets/1720338/21253124/0a1c3a2a-c397-11e6-9710-a52ca54c9713.jpg)

**Comment by oliverlorenz** [comment]
Hey! Sorry for the late response. Have you tried to set the DNS to your local network DNS provider? The example code in [README.md](https://github.com/oliverlorenz/phpMqttClient/blob/master/README.md) is using the 8.8.8.8 Google DNS

**Comment by oliverlorenz** [comment]
It seems there is no response. I will close this issue
