### ISSUE TITLE
React's EventLoop should be passed as constructor argument, to avoid creating multiple loops in the same process

### ISSUE THREAD

**Issue by docteurklein** [oliverlorenz/phpMqttClient#30]
Having multiple loops makes no sense when in the same thread, as the first loop blocks anyway.
Another benefit is to simplify the constructors, better manage dependencies, and share a single loop with other react libs.

**Comment by jjok** [comment]
Can you give an example? Where are there multiple loops?

**Comment by jjok** [comment]
`MqttClient` accepts `$loop` in the constructor already.

```
new MqttClient($loop, $connector, $version);
```

**Comment by docteurklein** [comment]
I must have dreamt it! sorry for the noise :)
