### ISSUE TITLE
Q: Is is possible to make TLS/PSK connections?

### ISSUE THREAD

**Issue by kernelguy** [oliverlorenz/phpMqttClient#8]
In the connector constructor it always uses the SocketClient Connector:
`$this->socketConnector = new \React\SocketClient\Connector($loop, $resolver);`

Would it be possible to somehow use the React\SocketClient\SecureConnector, perhaps by adding an options parameter?

We currently use the [Mosquitto extension](https://github.com/mgdm/Mosquitto-PHP), but your package seems much more suited for usage with ReactPHP.
We use a mix of TLS and PSK connections to a Mosquitto broker, but I think TLS would be fine for our PHP applicaitons.

**Comment by oliverlorenz** [comment]
Hey!

currently I don't have the time to follow your request. Sorry for that :( But its a great idea! So feel free to add this functionality and create a pull-request.

One wish: Don't add a parameter to the Connector, please add a SecureConnector class :)

Greetings
Oliver

**Comment by oliverlorenz** [comment]
Thanks to aedart, this feature is added now!
